# Generated by Django 4.0.3 on 2022-04-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile_operator_code',
            field=models.CharField(default='000', max_length=3, verbose_name='код мобильного оператора'),
        ),
    ]
