# Generated by Django 4.0.3 on 2022-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_distribution_client_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='clients',
            field=models.ManyToManyField(related_name='distribution_cli_filter', to='api.client', verbose_name='фильтр                                         свойств клиентов, на которых должна быть произведена рассылка(код мобильного оператора, тег)'),
        ),
    ]
