# Generated by Django 4.0.3 on 2022-04-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_distribution_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='clients_filter',
            field=models.JSONField(default={'mocs': [], 'tags': []}),
        ),
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='api.client', verbose_name='id клиента, которому отправили'),
        ),
        migrations.AlterField(
            model_name='message',
            name='distribution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_id', to='api.distribution', verbose_name='id рассылки, в рамках которой было отправлено сообщение'),
        ),
    ]
