# Generated by Django 4.0.3 on 2022-04-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_distribution_clients_filter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='distribution_id',
            new_name='distribution',
        ),
    ]
